with-expecter: true
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
issue-845-fix: true
packages:
  github.com/clambin/github-exporter/internal/collector:
    interfaces:
      StatClient:
  github.com/clambin/github-exporter/internal/stats:
    interfaces:
      GitHubClient:
  github.com/clambin/github-exporter/internal/stats/github:
    interfaces:
      Repositories:
      PullRequests:
