dir: '{{.InterfaceDir}}/mocks'
structname: '{{.InterfaceName}}'
pkgname: mocks
template: testify
filename: mocks.go
template-data:
  unroll-variadic: true
packages:
  github.com/clambin/github-exporter/internal/collector:
    interfaces:
      StatClient: {}
  github.com/clambin/github-exporter/internal/stats:
    interfaces:
      GitHubClient: {}
  github.com/clambin/github-exporter/internal/stats/github:
    interfaces:
      PullRequests: {}
      Repositories: {}
