// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/google/go-github/v70/github"
	mock "github.com/stretchr/testify/mock"
)

// Repositories is an autogenerated mock type for the Repositories type
type Repositories struct {
	mock.Mock
}

type Repositories_Expecter struct {
	mock *mock.Mock
}

func (_m *Repositories) EXPECT() *Repositories_Expecter {
	return &Repositories_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: _a0, _a1, _a2
func (_m *Repositories) Get(_a0 context.Context, _a1 string, _a2 string) (*github.Repository, *github.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *github.Repository
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*github.Repository, *github.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *github.Repository); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *github.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repositories_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repositories_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *Repositories_Expecter) Get(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Repositories_Get_Call {
	return &Repositories_Get_Call{Call: _e.mock.On("Get", _a0, _a1, _a2)}
}

func (_c *Repositories_Get_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *Repositories_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repositories_Get_Call) Return(_a0 *github.Repository, _a1 *github.Response, _a2 error) *Repositories_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repositories_Get_Call) RunAndReturn(run func(context.Context, string, string) (*github.Repository, *github.Response, error)) *Repositories_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *Repositories) ListByUser(_a0 context.Context, _a1 string, _a2 *github.RepositoryListByUserOptions) ([]*github.Repository, *github.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*github.Repository
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *github.RepositoryListByUserOptions) ([]*github.Repository, *github.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *github.RepositoryListByUserOptions) []*github.Repository); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *github.RepositoryListByUserOptions) *github.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *github.RepositoryListByUserOptions) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repositories_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type Repositories_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 *github.RepositoryListByUserOptions
func (_e *Repositories_Expecter) ListByUser(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Repositories_ListByUser_Call {
	return &Repositories_ListByUser_Call{Call: _e.mock.On("ListByUser", _a0, _a1, _a2)}
}

func (_c *Repositories_ListByUser_Call) Run(run func(_a0 context.Context, _a1 string, _a2 *github.RepositoryListByUserOptions)) *Repositories_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*github.RepositoryListByUserOptions))
	})
	return _c
}

func (_c *Repositories_ListByUser_Call) Return(_a0 []*github.Repository, _a1 *github.Response, _a2 error) *Repositories_ListByUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repositories_ListByUser_Call) RunAndReturn(run func(context.Context, string, *github.RepositoryListByUserOptions) ([]*github.Repository, *github.Response, error)) *Repositories_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositories creates a new instance of Repositories. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositories(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repositories {
	mock := &Repositories{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
