{
 "title": "GitHub",
 "tags": [ "grope" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active PR's",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    { "expr": "github_exporter_pulls > 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active issues",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    { "expr": "github_exporter_issues > 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Forks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "github_exporter_forks{archived=\"false\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stars",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "expr": "github_exporter_stars > 0", "legendFormat": "__auto" }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "call rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(github_exporter_http_requests_total[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "GitHub latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg (github_exporter_http_request_duration_seconds_sum / github_exporter_http_request_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg (github_exporter_inflight_requests{stage=\"post\"})",
     "legendFormat": "in flight"
    },
    {
     "expr": "avg (github_exporter_inflight_requests_max{stage=\"post\"})",
     "legendFormat": "max in flight"
    }
   ]
  }
 ]
}