// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/clambin/github-exporter/internal/stats/github"
	mock "github.com/stretchr/testify/mock"
)

// GitHubClient is an autogenerated mock type for the GitHubClient type
type GitHubClient struct {
	mock.Mock
}

type GitHubClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GitHubClient) EXPECT() *GitHubClient_Expecter {
	return &GitHubClient_Expecter{mock: &_m.Mock}
}

// GetPullRequestCountPage provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *GitHubClient) GetPullRequestCountPage(_a0 context.Context, _a1 string, _a2 string, _a3 int) (int, int, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequestCountPage")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (int, int, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) int); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) int); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int) error); ok {
		r2 = rf(_a0, _a1, _a2, _a3)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GitHubClient_GetPullRequestCountPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPullRequestCountPage'
type GitHubClient_GetPullRequestCountPage_Call struct {
	*mock.Call
}

// GetPullRequestCountPage is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
//   - _a3 int
func (_e *GitHubClient_Expecter) GetPullRequestCountPage(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *GitHubClient_GetPullRequestCountPage_Call {
	return &GitHubClient_GetPullRequestCountPage_Call{Call: _e.mock.On("GetPullRequestCountPage", _a0, _a1, _a2, _a3)}
}

func (_c *GitHubClient_GetPullRequestCountPage_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string, _a3 int)) *GitHubClient_GetPullRequestCountPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *GitHubClient_GetPullRequestCountPage_Call) Return(_a0 int, _a1 int, _a2 error) *GitHubClient_GetPullRequestCountPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *GitHubClient_GetPullRequestCountPage_Call) RunAndReturn(run func(context.Context, string, string, int) (int, int, error)) *GitHubClient_GetPullRequestCountPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoStats provides a mock function with given fields: _a0, _a1, _a2
func (_m *GitHubClient) GetRepoStats(_a0 context.Context, _a1 string, _a2 string) (github.RepoStats, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetRepoStats")
	}

	var r0 github.RepoStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (github.RepoStats, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) github.RepoStats); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(github.RepoStats)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GitHubClient_GetRepoStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoStats'
type GitHubClient_GetRepoStats_Call struct {
	*mock.Call
}

// GetRepoStats is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *GitHubClient_Expecter) GetRepoStats(_a0 interface{}, _a1 interface{}, _a2 interface{}) *GitHubClient_GetRepoStats_Call {
	return &GitHubClient_GetRepoStats_Call{Call: _e.mock.On("GetRepoStats", _a0, _a1, _a2)}
}

func (_c *GitHubClient_GetRepoStats_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *GitHubClient_GetRepoStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *GitHubClient_GetRepoStats_Call) Return(_a0 github.RepoStats, _a1 error) *GitHubClient_GetRepoStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GitHubClient_GetRepoStats_Call) RunAndReturn(run func(context.Context, string, string) (github.RepoStats, error)) *GitHubClient_GetRepoStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserReposPage provides a mock function with given fields: _a0, _a1, _a2
func (_m *GitHubClient) GetUserReposPage(_a0 context.Context, _a1 string, _a2 int) ([]string, int, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetUserReposPage")
	}

	var r0 []string
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]string, int, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []string); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) int); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GitHubClient_GetUserReposPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserReposPage'
type GitHubClient_GetUserReposPage_Call struct {
	*mock.Call
}

// GetUserReposPage is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 int
func (_e *GitHubClient_Expecter) GetUserReposPage(_a0 interface{}, _a1 interface{}, _a2 interface{}) *GitHubClient_GetUserReposPage_Call {
	return &GitHubClient_GetUserReposPage_Call{Call: _e.mock.On("GetUserReposPage", _a0, _a1, _a2)}
}

func (_c *GitHubClient_GetUserReposPage_Call) Run(run func(_a0 context.Context, _a1 string, _a2 int)) *GitHubClient_GetUserReposPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *GitHubClient_GetUserReposPage_Call) Return(_a0 []string, _a1 int, _a2 error) *GitHubClient_GetUserReposPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *GitHubClient_GetUserReposPage_Call) RunAndReturn(run func(context.Context, string, int) ([]string, int, error)) *GitHubClient_GetUserReposPage_Call {
	_c.Call.Return(run)
	return _c
}

// NewGitHubClient creates a new instance of GitHubClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitHubClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitHubClient {
	mock := &GitHubClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
