// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/clambin/github-exporter/internal/stats/github"
	mock "github.com/stretchr/testify/mock"
)

// NewStatClient creates a new instance of StatClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatClient {
	mock := &StatClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StatClient is an autogenerated mock type for the StatClient type
type StatClient struct {
	mock.Mock
}

type StatClient_Expecter struct {
	mock *mock.Mock
}

func (_m *StatClient) EXPECT() *StatClient_Expecter {
	return &StatClient_Expecter{mock: &_m.Mock}
}

// GetRepoStats provides a mock function for the type StatClient
func (_mock *StatClient) GetRepoStats(context1 context.Context, strings []string, strings1 []string) ([]github.RepoStats, error) {
	ret := _mock.Called(context1, strings, strings1)

	if len(ret) == 0 {
		panic("no return value specified for GetRepoStats")
	}

	var r0 []github.RepoStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string) ([]github.RepoStats, error)); ok {
		return returnFunc(context1, strings, strings1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string) []github.RepoStats); ok {
		r0 = returnFunc(context1, strings, strings1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]github.RepoStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, []string) error); ok {
		r1 = returnFunc(context1, strings, strings1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StatClient_GetRepoStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoStats'
type StatClient_GetRepoStats_Call struct {
	*mock.Call
}

// GetRepoStats is a helper method to define mock.On call
//   - context1 context.Context
//   - strings []string
//   - strings1 []string
func (_e *StatClient_Expecter) GetRepoStats(context1 interface{}, strings interface{}, strings1 interface{}) *StatClient_GetRepoStats_Call {
	return &StatClient_GetRepoStats_Call{Call: _e.mock.On("GetRepoStats", context1, strings, strings1)}
}

func (_c *StatClient_GetRepoStats_Call) Run(run func(context1 context.Context, strings []string, strings1 []string)) *StatClient_GetRepoStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StatClient_GetRepoStats_Call) Return(repoStatss []github.RepoStats, err error) *StatClient_GetRepoStats_Call {
	_c.Call.Return(repoStatss, err)
	return _c
}

func (_c *StatClient_GetRepoStats_Call) RunAndReturn(run func(context1 context.Context, strings []string, strings1 []string) ([]github.RepoStats, error)) *StatClient_GetRepoStats_Call {
	_c.Call.Return(run)
	return _c
}
