name: Build

on:
  push:
    branches:
      - main
      - codecov

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      target: github-exporter