name: Build

on:
  push:
    branches:
      - main
      - gitbhub58

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      target: github-exporter