name: Test

on:
  push:
    branches-ignore:
      - main
      - github58

  pull_request_target:

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    with:
      all-tests: true
